#+title: Notes

diff from code claude deleted
#+begin_src diff
modified   src/WSHS.hs
@@ -20,15 +20,22 @@ data Configuration = Configuration
 instance D.FromDhall Configuration

+data Command
+  = Bootstrap
+    { configPath :: FilePath
+    , workstation :: String
+    }
+  deriving (Show)
+
+
 data Options = Options
-  { configPath :: FilePath
-  , workstation :: String
+  { command :: Command
   }
   deriving (Show)


-optionsParser :: Parser Options
-optionsParser = Options
+bootstrapParser :: Parser Command
+bootstrapParser = Bootstrap
   <$> strArgument
       ( metavar "CONFIG"
      <> help "Path to the configuration dhall file" )
@@ -37,6 +44,19 @@ optionsParser = Options
      <> help "Name of the current workstation" )


+commandParser :: Parser Command
+commandParser = subparser
+  ( command "bootstrap"
+    ( info bootstrapParser
+      ( progDesc "Bootstrap a new workstation" )
+    )
+  )
+
+
+optionsParser :: Parser Options
+optionsParser = Options <$> commandParser
+
+
 parseOptions :: IO Options
 parseOptions =
   execParser $ info (optionsParser <**> helper)
@@ -50,6 +70,8 @@ parseOptions =
 main :: IO ()
 main = do
   opts <- parseOptions
-  cfg <- D.input D.auto (T.pack $ configPath opts)
-  print (cfg :: Configuration)
-  putStrLn $ "Workstation: " ++ workstation opts
+  case command opts of
+    Bootstrap cfgPath ws -> do
+      cfg <- D.input D.auto (T.pack cfgPath)
+      print (cfg :: Configuration)
+      putStrLn $ "Workstation: " ++ ws

#+end_src







my config from ws project:



#+begin_src shell
workstation_props_angrist=()
workstation_props_angrist+=(ws_prop_current_settings_symlink)
workstation_props_angrist+=(ws_prop_dotfiles_git_track)
workstation_props_angrist+=(ws_prop_nix_daemon_installed)
workstation_props_angrist+=(ws_prop_nix_global_config)
workstation_props_angrist+=(ws_prop_df_dotfiles)
workstation_props_angrist+=(ws_prop_nix_home_manager)
workstation_props_angrist+=(ws_prop_homebrew_bundle)
workstation_props_angrist+=(ws_prop_linux_bw_cli_installed)
workstation_props_angrist+=(ws_prop_bitwarden_secrets) # needs brew bundle

workstation_props_dotfiles_angrist() {
  ws_df_dotfile --ln --dot bashrc
  ws_df_dotfile --ln --dot ghci
  ws_df_dotfile --ln --dot gitconfig
  ws_df_dotfile --ln --dot hammerspoon
  ws_df_dotfile --ln --dot nix-channels
  ws_df_dotfile --ln --dot npmrc
  ws_df_dotfile --ln --dot reddup.yml
  ws_df_dotfile --ln --dot zshrc

#  ws_df_dotfile --ln Brewfile
#  ws_df_dotfile --ln Brewfile.lock.json
  ws_df_dotfile --ln bitbar

  ws_df_dotfile --ln --dot --dir config/git
  ws_df_dotfile --ln --dot --dir config/doom
}

# since I am working on this frequently, and often just using the currently installed version,
# I want the 'git' origin value (so I can push after testing a fresh setup)
WS_REPO_ORIGIN="git@github.com:joelmccracken/ws.git";


workstation_props_aeglos=("${workstation_props_angrist[@]}")
workstation_props_dotfiles_aeglos() {
  workstation_props_dotfiles_angrist
}


# config just for CI below
workstation_props_ci_macos=("${workstation_props_angrist[@]}")

workstation_props_ci_ubuntu=("${workstation_props_angrist[@]}")

workstation_props_dotfiles_ci_macos() {
  workstation_props_dotfiles_angrist
}

workstation_props_dotfiles_ci_ubuntu() {
  workstation_props_dotfiles_angrist
}

ws_prop_linux_bw_cli_installed()
{
  if [[ "$(uname)" == 'Linux' ]]; then
    if which bw &>/dev/null; then
      echo "found bw command";
      return 0
    else
      echo "did not find bw command"
      return 1
    fi
  else
    # only care
    return 0
  fi
}

ws_prop_linux_bw_cli_installed_fix()
{

  apt update -y
  apt install -y wget unzip

  local dldir
  dldir="$(mktemp -d)"
  ( cd "$dldir";
    wget -O bw.zip 'https://bitwarden.com/download/?app=cli&platform=linux'
    unzip bw.zip
    mkdir -p "$HOME/.local/bin"
    install ./bw "$HOME/.local/bin/bw"
  )
  return 0
}


#+end_src






#+begin_src shell
WS_PROP_DF_GIT_DIR__default() {
  printf ".git-dotfiles"
}
: "${WS_PROP_DF_GIT_DIR:=}"

ws_prop_dotfiles_git_track() {
  local gd
  gd="$(ws_lookup WS_PROP_DF_GIT_DIR)"
  if [ -d "$HOME/$gd" ]; then
    echo "git directory at $HOME/$gd exists"
    return 0
  else
    echo "git directory at $HOME/$gd not found" 1>&2
    return 1
  fi
}

ws_prop_dotfiles_git_track_fix() {
  export GIT_DIR
  GIT_DIR="$(ws_lookup WS_PROP_DF_GIT_DIR)"
  ( cd "$HOME";
    git init .
    git config --local --get-all core.bare true >/dev/null && \
      git config --local --replace-all core.bare false true
  )
  return 0
}


#+end_src



#+begin_src haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE ExtendedDefaultRules #-}
-- {-# LANGUAGE DeriveGeneric     #-}
-- {-# LANGUAGE DeriveAnyClass    #-}
-- {-# LANGUAGE DerivingStrategies    #-}
-- {-# LANGUAGE OverloadedRecordDot #-}
-- {-# LANGUAGE TemplateHaskell   #-}
-- {-# LANGUAGE TypeApplications #-}
-- {-# LANGUAGE DuplicateRecordFields #-}
-- {-# LANGUAGE GeneralizedNewtypeDeriving #-}
-- {-# LANGUAGE TypeFamilies #-}
-- {-# LANGUAGE FlexibleInstances #-}
-- {-# LANGUAGE ScopedTypeVariables #-}
-- {-# LANGUAGE RankNTypes #-}


module WSHS.Properties where

import Options.Applicative
import Options.Applicative qualified as App
import Data.Text (Text)
import qualified Data.Text as T
import Data.Either (isRight)
import Shh (exe, devNull, (&>),  )
import Data.Yaml (decodeFileThrow)
-- import Data.Maybe (isJust)
import qualified Data.Set as Set
import Control.Monad (void, forM_)
import Control.Monad.IO.Class
import WSHS.Types
import WSHS.Types.Configuration
import Control.Monad.State
import Control.Monad.Reader
import WSHS.Commands qualified as Cmd
import WSHS.Util

class Property p where
  checker :: WS Bool
  fixer :: WS ()
  dependencies :: WS [Property]


newtype XCodeCliTools = XCodeCliTools ()






#+end_src
* TODO ideas
- test run in docker containers for linux specific
* features to build of mixed priority
** TODO download/install nix
** TODO create a file on filesystem at spot
- sudo nopasswd
-
* all props from bash version

#+begin_example
joelmccracken@glamdring> rg 'ws_prop_.*fix.*\(\)'                                                                                                                                                   ~/.local/share/ws
lib/properties/nix.bash
19:ws_prop_nix_daemon_installed_fix() {
86:ws_prop_nix_global_config_fix () {
140:ws_prop_nix_home_manager_fix() {

lib/properties/secrets.bash
14:ws_prop_bitwarden_secrets_fix() {

lib/properties/dotfiles.bash
43:ws_prop_df_dotfiles_fix() {

lib/properties.bash
70:ws_prop_check_mac_cli_tools_fix () {
84:ws_prop_check_mac_homebrew_installed_fix() {
96:ws_prop_check_mac_git_installed_fix() {
108:ws_prop_check_linux_git_installed_fix() {
131:ws_prop_check_workstation_dir_fix() {
157:ws_prop_check_workstation_repo_fix() {
183:ws_prop_dotfiles_git_track_fix() {
215:ws_prop_config_exists_fix() {
323:ws_prop_current_settings_symlink_fix() {
361:ws_prop_homebrew_bundle_fix() {

#+end_example
* virutla machine notes

macos 14 VM. currently have snapshot of virutally "brand new" vm

#+begin_src sh
  # from host:
  rm ~/vmwareshared/* # remove existing shared
  cp ./result/bin/wshs test/sample_configs/just_nix.yml ~/vmwareshared/


  (rm -f ~/vmwareshared/*; cp ./result/bin/wshs test/sample_configs/just_nix.yml ~/vmwareshared/)


  # from guest
  mkdir -p ~/testing
  cd ~/testing
  cp /Volumes/VMware\ Shared\ Folders/vmwareshared/* .
  ./wshs bootstrap config.yml aeglos


  # one easy to copy/paste line
  (mkdir -p ~/testing; cd ~/testing; cp /Volumes/VMware\ Shared\ Folders/vmwareshared/* .; ./wshs bootstrap just_nix.yml aeglos)
#+end_src
- TODO add some kind of test support; something like:
  - command to restore snapshot
  - command to start again
  - command


- commands to automate

#+begin_src sh
  # start a VM
  /Applications/VMware\ Fusion.app/Contents/Library/vmrun -T fusion revertToSnapshot ~/Virtual\ Machines.localized/macOS\ 14.vmwarevm/macOS\ 14.vmx 'Snapshot 4'
  /Applications/VMware\ Fusion.app/Contents/Library/vmrun -T fusion start ~/Virtual\ Machines.localized/macOS\ 14.vmwarevm/macOS\ 14.vmx gui
  /Applications/VMware\ Fusion.app/Contents/Library/vmrun -T fusion -gu joel -gp password runScriptInGuest ~/Virtual\ Machines.localized/macOS\ 14.vmwarevm/macOS\ 14.vmx -interactive /bin/bash "osascript -e 'tell app \"Terminal\" to do script \"mkdir -p ~/testing; cd ~/testing; cp /Volumes/VMWare\\\ Shared\\\ Folders/vmwareshared/* .; ./wshs bootstrap just_nix.yml aeglos\"'"



#+end_src


** vmrun help
#+begin_quote
joelmccracken@glamdring> /Applications/VMware\ Fusion.app/Contents/Library/vmrun -h
Invalid argument: -h
vmrun version 1.17.0 build-24832108

Usage: vmrun [AUTHENTICATION-FLAGS] COMMAND [PARAMETERS]



AUTHENTICATION-FLAGS
--------------------
These must appear before the command and any command parameters.

   -T <hostType> (ws|fusion)
   -vp <password for encrypted virtual machine>
   -gu <userName in guest OS>
   -gp <password in guest OS>



POWER COMMANDS           PARAMETERS           DESCRIPTION
--------------           ----------           -----------
start                    Path to vmx file     Start a VM or Team
                         [gui|nogui]

stop                     Path to vmx file     Stop a VM or Team
                         [hard|soft]

reset                    Path to vmx file     Reset a VM or Team
                         [hard|soft]

suspend                  Path to vmx file     Suspend a VM or Team
                         [hard|soft]

pause                    Path to vmx file     Pause a VM

unpause                  Path to vmx file     Unpause a VM



SNAPSHOT COMMANDS        PARAMETERS           DESCRIPTION
-----------------        ----------           -----------
listSnapshots            Path to vmx file     List all snapshots in a VM
                         [showTree]

snapshot                 Path to vmx file     Create a snapshot of a VM
                         Snapshot name

deleteSnapshot           Path to vmx file     Remove a snapshot from a VM
                         Snapshot name
                         [andDeleteChildren]

revertToSnapshot         Path to vmx file     Set VM state to a snapshot
                         Snapshot name



NETWORKADAPTER COMMANDS  PARAMETERS           DESCRIPTION
-----------------------  ----------           -----------
listNetworkAdapters      Path to vmx file     List all network adapters in a VM


addNetworkAdapter        Path to vmx file     Add a network adapter on a VM
                         Network adapter type
                         [Host nework]


setNetworkAdapter        Path to vmx file     Update a network adapter on a VM
                         Network adapter index
                         Network adapter type
                         [Host network]


deleteNetworkAdapter     Path to vmx file     Remove a network adapter on a VM
                         Network adapter index




HOST NETWORK COMMANDS    PARAMETERS           DESCRIPTION
---------------------    ----------           -----------
listHostNetworks                              List all networks in the host

listPortForwardings      Host network name    List all available port forwardings on a host network


setPortForwarding        Host network name    Add or update a port forwarding on a host network
                         Protocol
                         Host port
                         Guest ip
                         Guest port
                         [Description]

deletePortForwarding     Host network name    Delete a port forwarding on a host network
                         Protocol
                         Host port




GUEST OS COMMANDS        PARAMETERS           DESCRIPTION
-----------------        ----------           -----------
runProgramInGuest        Path to vmx file     Run a program in Guest OS
                         [-noWait]
                         [-activeWindow]
                         [-interactive]
                         Complete-Path-To-Program
                         [Program arguments]

fileExistsInGuest        Path to vmx file     Check if a file exists in Guest OS
                         Path to file in guest

directoryExistsInGuest   Path to vmx file     Check if a directory exists in Guest OS
                         Path to directory in guest

setSharedFolderState     Path to vmx file     Modify a Host-Guest shared folder
                         Share name
                         Host path
                         writable | readonly

addSharedFolder          Path to vmx file     Add a Host-Guest shared folder
                         Share name
                         New host path

removeSharedFolder       Path to vmx file     Remove a Host-Guest shared folder
                         Share name

enableSharedFolders      Path to vmx file     Enable shared folders in Guest
                         [runtime]

disableSharedFolders     Path to vmx file     Disable shared folders in Guest
                         [runtime]

listProcessesInGuest     Path to vmx file     List running processes in Guest OS

killProcessInGuest       Path to vmx file     Kill a process in Guest OS
                         process id

runScriptInGuest         Path to vmx file     Run a script in Guest OS
                         [-noWait]
                         [-activeWindow]
                         [-interactive]
                         Interpreter path
                         Script text

deleteFileInGuest        Path to vmx file     Delete a file in Guest OS
                         Path in guest

createDirectoryInGuest   Path to vmx file     Create a directory in Guest OS
                         Directory path in guest

deleteDirectoryInGuest   Path to vmx file     Delete a directory in Guest OS
                         Directory path in guest

CreateTempfileInGuest    Path to vmx file     Create a temporary file in Guest OS

listDirectoryInGuest     Path to vmx file     List a directory in Guest OS
                         Directory path in guest

CopyFileFromHostToGuest  Path to vmx file     Copy a file from host OS to guest OS
                         Path on host
                         Path in guest

CopyFileFromGuestToHost  Path to vmx file     Copy a file from guest OS to host OS
                         Path in guest
                         Path on host

renameFileInGuest        Path to vmx file     Rename a file in Guest OS
                         Original name
                         New name

typeKeystrokesInGuest    Path to vmx file     Type Keystrokes in Guest OS
                         keystroke string

connectNamedDevice       Path to vmx file     Connect the named device in the Guest OS
                         device name

disconnectNamedDevice    Path to vmx file     Disconnect the named device in the Guest OS
                         device name

captureScreen            Path to vmx file     Capture the screen of the VM to a local file
                         Path on host

writeVariable            Path to vmx file     Write a variable in the VM state
                         [runtimeConfig|guestEnv|guestVar]
                         variable name
                         variable value

readVariable             Path to vmx file     Read a variable in the VM state
                         [runtimeConfig|guestEnv|guestVar]
                         variable name

getGuestIPAddress        Path to vmx file     Gets the IP address of the guest
                         [-wait]



GENERAL COMMANDS         PARAMETERS           DESCRIPTION
----------------         ----------           -----------
list                                          List all running VMs

upgradevm                Path to vmx file     Upgrade VM file format, virtual hw

installTools             Path to vmx file     Install Tools in Guest

checkToolsState          Path to vmx file     Check the current Tools state

deleteVM                 Path to vmx file     Delete a VM

clone                    Path to vmx file     Create a copy of the VM
                         Path to destination vmx file
                         full|linked
                         [-snapshot=Snapshot Name]
                         [-cloneName=Name]



Template VM COMMANDS     PARAMETERS           DESCRIPTION
---------------------    ----------           -----------
downloadPhotonVM         Path for new VM      Download Photon VM





Examples:


Starting a virtual machine with Fusion on a Apple host
   vmrun -T fusion start "/Users/xxxxx/Virtual Machines.localized/VMwarePhotonOS.vmwarevm/VMwarePhotonOS.vmx"


Running a program in a virtual machine with Fusion on a Apple host with Windows guest
   vmrun -T fusion -gu guestUser -gp guestPassword runProgramInGuest "/Users/xxxxx/Virtual Machines.localized/Windows.vmwarevm/Windows.vmx" "c:\Program Files\myProgram.exe"


Creating a snapshot of a virtual machine with Fusion on a Apple host
   vmrun -T fusion snapshot "/Users/xxxxx/Virtual Machines.localized/Windows.vmwarevm/Windows.vmx" mySnapshot


Reverting to a snapshot with Fusion on a Apple host
   vmrun -T fusion revertToSnapshot "/Users/xxxxx/Virtual Machines.localized/Windows.vmwarevm/Windows.vmx" mySnapshot


Deleting a snapshot with Fusion on a Apple host
   vmrun -T fusion deleteSnapshot "/Users/xxxxx/Virtual Machines.localized/Windows.vmwarevm/Windows.vmx" mySnapshot


Enabling Shared Folders with Fusion on a Apple host
   vmrun -T fusion enableSharedFolders "/Users/xxxxx/Virtual Machines.localized/Windows.vmwarevm/Windows.vmx"
#+end_quote
* thinking about file operation needs
- different states to be able to declare
  - define some file is a symlink to another file
  - file has contents
    - from a src file,
    - or from a src snippet in config (entire file spec)
      - either specifying entire file
      - or spec just a snippet (demarcated with fences (?))
  - file has permissions/ownership
  - file is a directory with contents
    - either specifying from filesystem src
    - or specifying from config
  - file is a symlink to a directory
  - allowing "extra" files in a dir
** another way to think about:
- either "match this spec" or "match this part of FS"
* setting up new VM
- in vmware fusion, create a new vm
- drag macos14install.dmg to interface (rn its in ~)
- macos 14 for OS
- defaults for other stuff:
  - memory 4GB
  - hard disk 80GB
  - network shared with mac(NAT)
  - 2 cpu cores, CD/DVD,USB Controller, Sound Card
- vmware promt about side channel attack mitigations, TODO disable later
- booting installer, following defaults
- ... select defaults, skip when possible
- (skip signing in to icloud - will I need to do it later?)
- account: username: "user", password: "password"
- new york closest city
- (fix name to remove the 2 from the "internal" name)
- install vmware tools
  - required for file sharing/transferring test files
  - donwload darwin.iso
  - (struggling to figure out how to get the tools mounted)
  - unmount the intaller dvd/iso
  - choose disk or disk image, navigate to darwin.iso in downloads
  - connect cd/dvd
  - install vmware tools
    - defaults, get to point where told pjermissions required
    - open system settings, click "allow"
    - told need to restart (do restart, seems to have to happen immediately)
    - after restart, eject vmware tools
- enable shared folders
  - check mark in settings
  - select ~/vmwareshared
  - check that VM can see the shared info
- do final eject of vmware tools
- drag vmwareshared  to finder favorites
- Open terminal, drag to dock
- rename file on disk to match internal vm name
  - select "i moved it"
  - it seems that all of the names for this are now "macOS 14"
- looked at internals of vm name, looks like "2" postfix is still in a lot of places
- STARTING OVER this " 2" postfix is gonna drive me crazy
* setting up new vm redux
- in vmware fusion, create new vm. drag macos14install.dcmg to interface
- pick macos 14
- customize settings, rename to `macOS_14`
- defaults for other stuff:
  - memory 4GB
  - hard disk 80GB
  - network shared with mac(NAT)
  - 2 cpu cores, CD/DVD,USB Controller, Sound Card
- TODO disable side channel hardware mitigations later
- booting installer, following defaults
- ... select defaults, skip any setup when possible
  - looked tosee if I could change the names of files in vmdir, no good. they
    look ok now though since I set a good vm name from the beginning
  - skip migration assistant
  - skip icloud/appleid
    - will I need to do it later?
  - skip location services
- account: username: "user", password: "password"
- new york closest city
- skip screen time setup
- take snapshot "post-install"
- unmount the intaller dvd/iso
- set up vmware tools for file sharing
  - download vmware tools iso (darwin.iso)
  - select image via dvd button
  - "connect cd/dvd"
  - do installer
    - allow, open system menu and press allow button also
  - restart logic of installer is weird;
    - I tried to restart but error "close installer to restart"
    - had to press installer blue "restart" button to actually close it
  - try enabling file sharing in menu
    - "sharing settings" button
    - enable shared folders
    - select ~/vmwareshared
    - its not working? expected dir is empy
  - didn't work! went in and found security had blocked the extension again?
    - re-approaved it then "restart"
  - sharing now seems to work
  - pull vmwareshared dir to finder favorites
  - "vmware-tools-daemon" would like to ...
    - allow, approve, open system settings and OK/toggle
  - eject vmware tools iso
- open terminal, drag to dock
- snapshot: "post-vmwaretools-setup-sharing-works"
  - can taked snapshot with Cmd+shift+s
  - manage them with Cmd+s
  - click outide of vm first, need vm "chrome" selected
- going to try first run
- shut down, disable side channel mitigations, start back up
- run the test script once, hit permissions, killed script
  - allow vmtools-daemon access terminal
  - allow terminal access network volume
  - STARTING_SNAPSHOT='after-allow-vmware-tools-permissions'
- run the test script again, hit permissions, kill script
- hit an anohter jpermisssionms thing but so far along... in the middle of the
  nix install
  - I _think_ this is basically flagging the edit of fstab. going to try
    pre-enabling full disk access
  - done; we'll see if the dialog still bothers me
- SUCCESS. the entire basic run of wshs bootstrap proceeded without issue
- next time, perhaps try disabling SIP, adding the required permissions via a
  cli sqlite tool, and then reenabling SIP
