name: Build and Release

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: funstation-x86_64-darwin
      - uses: actions/download-artifact@v4
        with:
          name: funstation-aarch64-darwin
      - uses: actions/download-artifact@v4
        with:
          name: funstation-x86_64-linux
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build (master)
          prerelease: true
          files: |
            funstation-x86_64-darwin
            funstation-aarch64-darwin
            funstation-x86_64-linux
